apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickettotal
  labels:
    app: tickettotal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickettotal
  template:
    metadata:
      labels:
        app: tickettotal
    spec:
      containers:
        - name: tickettotal
          image: username/tickettotal:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5